name: k19_player
description: "A music player for OpenSubsonic"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.1
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  provider: ^6.1.2
  tuple: ^2.0.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.3
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.3
  build_runner: ^2.4.8

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  image_path_android: "assets/images/icon.png"
  android: true
  adaptive_icon_background: "#fcfcfc"
  adaptive_icon_foreground: "assets/images/icon.png"
  adaptive_icon_monochrome: "assets/images/icon.png"
  min_sdk_android: 21 

